#!/bin/bash
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a00/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a01/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a02/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a03/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a04/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a05/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a06/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a07/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a08/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a09/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a10/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a11/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a12/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/a13/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/r00/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u00/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u01/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u02/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u03/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u04/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u05/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u06/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u07/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u08/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u09/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u10/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u11/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u12/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u13/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u14/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u15/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u16/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u17/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u18/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u19/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u20/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u21/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u22/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u23/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u24/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u25/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u26/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u27/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u28/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u29/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u30/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u31/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u32/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u33/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u34/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u35/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u36/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u37/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u38/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u39/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u40/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u41/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u42/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u43/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u44/generated/
qsub tscc.sh
cd ../../
cd /home/davids4/projects/smirnoff-host-guest/a-bam-p/u45/generated/
qsub tscc.sh
cd ../../
